version: '3'

services:
  redis:
    container_name: redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - rate-limiter
  aplicacao:
    container_name: aplicacao_rate_limiter
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - rate-limiter

networks:
  rate-limiter:
    name: rate-limiter
    driver: bridge